---
- name: Utility present Debian-like
  ansible.builtin.apt:
      name:
          - nfs-common
          - nfs4-acl-tools
      state: present
  when: ansible_os_family == 'Debian'

- name: Check mountpoint exist
  ansible.builtin.file:
      path: "{{ mount_nfs_path }}"
      state: directory
      mode: "{{ mount_nfs_permission }}"
      owner: root
      group: root

- name: Mount network share
  ansible.posix.mount:
      src: "{{ mount_nfs_source }}"
      path: "{{ mount_nfs_path }}"
      fstype: "{{ mount_nfs_fstype }}"
      opts: "{{ mount_nfs_opts }}"
      state: mounted
