---
- name: Utility present Debian-like
  ansible.builtin.apt:
     name:
        - nfs-common
        - nfs4-acl-tools
     state: present
  when: ansible_os_family == 'Debian'

- name: Check mountpoint exist
  ansible.builtin.file:
     path: "{{ mount_media_path }}"
     state: directory
     mode: "{{ mount_media_permission }}"
     owner: root
     group: root

- name: Mount network share
  ansible.posix.mount:
     src: "{{ mount_media_source }}"
     path: "{{ mount_media_path }}"
     fstype: "{{ mount_media_fstype }}"
     opts: "{{ mount_media_opts }}"
     state: mounted
